### PR TITLE
Add multiple-object segmentation feature and fine-tuning on multiple images

### PR DESCRIPTION
**Pull request by mlzoo**
Add multiple-object segmentation feature and fine-tuning on multiple images.

### CODE REVIEW

**Comment by OSSome01** [comment]
Is this for multiple-object segmentation of the same class? or is it also for multiple classes?

**Comment by mlzoo** [comment]
This is for multiple objects of the same class appearing in the one image.

**Comment by mlzoo** [comment]
> Is this for multiple-object segmentation of the same class? or is it also for multiple classes?

This is for multiple objects of the same class appearing in the one image.

**Comment by Skwarson96** [comment]
Hi! @mlzoo is your code working? I found some syntax errors and many more errors, mainly: "local variable ... referenced before assignment"

**Comment by ZrrSkywalker** [comment]
@mlzoo Hi, thanks very much for your contribution! It means a lot for PerSAM to tackle multi-object scenarios.

**Comment by mlzoo** [comment]
> Hi! @mlzoo is your code working? I found some syntax errors and many more errors, mainly: "local variable ... referenced before assignment"

Hi can you give me the error information?

**Comment by mlzoo** [comment]
> @mlzoo At the beginning in line 67:
> 
>     print('Training size:', len()
> 
>                             ^^^^^
> 
> SyntaxError: Generator expression must be parenthesized
> 
> 

My fault! Please delete that line... I will fix the bug later.

**Comment by Skwarson96** [comment]
@mlzoo of course, but despite this, there are still errors, for example line 70 in persam_f_multi_obj.py: 
`training_size = int(os.listdir(os.path.join(images_path, obj_name)))  * args.training_percentage) `
I thing it should be: 
`training_size = int(len(os.listdir(os.path.join(images_path, obj_name))) * args.training_percentage)`
But when I fix it I still get a lot of errors. Lot of variables are referenced before assignment

**Pull request merged**
